apiVersion: apps/v1
kind: Deployment
metadata:
  name: turnik-bot
  namespace: turnik-bot
  labels:
    app: turnik-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turnik-bot
  template:
    metadata:
      labels:
        app: turnik-bot
    spec:
      containers:
        - name: turnik-bot
          image: fullpipe/turnik-bot:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
              subPath: turnik-bot
            - name: tz-config
              mountPath: /etc/localtime
          envFrom:
            - secretRef:
                name: turnik-bot
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: turnik-bot-db-pvc
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Moscow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turnik-bot-db-pvc
  namespace: turnik-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
