version: '3.1'
services:
  app:
    build: .
    restart: always
    environment:
      DB_TYPE: sqlite3
      TELEGRAM_TOKEN: YOUTOKETFROMBOTFATHER
      TELEGRAM_URL: https://api.telegram.org #or your proxy http://IP:30012 @see https://github.com/fullpipe/tele-proxy
